# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lower_limit_cpp <- function(u, v, cum_pi) {
    .Call(`_polyiden_lower_limit_cpp`, u, v, cum_pi)
}

upper_limit_cpp <- function(u, v, cum_pi) {
    .Call(`_polyiden_upper_limit_cpp`, u, v, cum_pi)
}

